export const PROJECTS                 = "PROJECTS"
export const PROJECT_SELECTED         = "PROJECT_SELECTED"
export const PROJECT_MERGE            = "PROJECT_MERGE"
export const PROJECT_TOGGLE_STATUS    = "PROJECT_TOGGLE_STATUS"
export const PROJECT_DELETE           = "VUEX_TYPES_PROJECT_DELETE"
